version: "3"
services:
  fs-intake-postgres:
    image: postgres:9.6.3
    networks:
      - fs-intake
    environment:
      POSTGRES_PASSWORD: postgres
  fs-intake-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile-server
    ports:
      - "8080:8080"
    volumes:
      - ../server:/usr/src/app
      - ../frontend/src/assets/img:/usr/src/app/frontend-assets/img:ro
      - ../frontend/src/assets/content:/usr/src/app/frontend-assets/content:ro
      - /usr/src/app/node_modules
    tmpfs:
      - /usr/src/app
    depends_on:
      - fs-intake-postgres
    networks:
      - fs-intake
    links:
      - fs-intake-postgres
  fs-intake-frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile-frontend
    image: fs-intake-frontend
    ports:
      - "4200:4200"
    volumes:
      - ../frontend:/usr/src/app
      - /dev/shm:/dev/shm
      - /usr/src/app/node_modules
      - /usr/src/app/dist
      - /usr/src/app/e2e-test-results
    depends_on:
      - fs-intake-server
    networks:
      - fs-intake
    user: root
    command: ng serve --configuration=docker --host 0.0.0.0
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - fs-intake-postgres
    networks:
      - fs-intake
    links:
      - fs-intake-postgres
networks:
  fs-intake:
